# Generated by Django 5.1.6 on 2026-05-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0005_vpnclient_contact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientExpirationReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_days", models.PositiveIntegerField()),
                ("expires_at_snapshot", models.DateTimeField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("recipient_hash", models.CharField(blank=True, max_length=64)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiration_reminder_logs",
                        to="vpn.vpnclient",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "threshold_days", "expires_at_snapshot"),
                        name="unique_client_expiration_reminder",
                    )
                ],
            },
        ),
    ]
