# Generated by Django 5.1.6 on 2026-08-03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0006_clientexpirationreminderlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="XHTTPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "client_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("xray_email", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("disabled", "Отключено"),
                            ("deleted", "Удалено"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "disable_reason",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("manual", "Вручную"),
                            ("client", "Отключён родительский клиент"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("config_blob_encrypted", models.TextField()),
                ("config_hash", models.CharField(max_length=64)),
                ("last_applied_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xhttp_devices",
                        to="vpn.vpnclient",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="xhttpdevice",
            constraint=models.UniqueConstraint(
                fields=("client", "name"),
                name="unique_xhttp_device_name_per_client",
            ),
        ),
    ]
