# Generated by Django 5.1.6 on 2026-08-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('vpn', '0007_xhttpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclient',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_clients', to='customers.clientdevice'),
        ),
    ]
