# Generated by Django 5.1.6 on 2026-08-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_legacy_vpn_clients'),
        ('servers', '0003_server_public_endpoint'),
        ('vpn', '0010_backfill_xhttpdevice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='xhttpdevice',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xhttp_devices', to='servers.server'),
        ),
        migrations.AlterField(
            model_name='xhttpdevice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xhttp_devices', to='vpn.vpnclient'),
        ),
        migrations.AlterField(
            model_name='xhttpdevice',
            name='disable_reason',
            field=models.CharField(choices=[('none', 'Нет'), ('manual', 'Вручную'), ('client', 'Недоступен аккаунт/устройство')], default='none', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='xhttpdevice',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_xhttp_name_per_device'),
        ),
    ]
