# Generated by Django 5.1.6 on 2026-08-18 07:39

import vpn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_clientdevice_expires_at_and_more'),
        ('vpn', '0014_finalize_xhttp_device_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnclient',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=vpn.models.protect_non_deleted_connection, related_name='vpn_clients', to='customers.clientdevice'),
        ),
        migrations.AlterField(
            model_name='xhttpdevice',
            name='device',
            field=models.ForeignKey(on_delete=vpn.models.protect_non_deleted_connection, related_name='xhttp_devices', to='customers.clientdevice'),
        ),
    ]
