from .base import *
import os

DEBUG = False

DJANGO_FORCE_SSL = os.getenv("DJANGO_FORCE_SSL", "0") == "1"

SESSION_COOKIE_SECURE = DJANGO_FORCE_SSL
CSRF_COOKIE_SECURE = DJANGO_FORCE_SSL
SECURE_SSL_REDIRECT = DJANGO_FORCE_SSL
SECURE_HSTS_SECONDS = 31536000 if DJANGO_FORCE_SSL else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = DJANGO_FORCE_SSL
SECURE_HSTS_PRELOAD = DJANGO_FORCE_SSL
