# Generated by Django 5.1.6 on 2026-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientportalaccess",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
