# Generated by Django 5.1.6 on 2026-04-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_clientportalaccess_token_encrypted"),
        ("vpn", "0004_vpnclient_limits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientportalaccess",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Доступ в кабинет клиента",
                "verbose_name_plural": "Доступы в кабинет клиента",
            },
        ),
        migrations.CreateModel(
            name="ClientRenewalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("dismissed", "Отклонена"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("operator_note", models.TextField(blank=True)),
                ("created_from_portal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_requests",
                        to="vpn.vpnclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на продление",
                "verbose_name_plural": "Заявки на продление",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["new", "in_progress"])),
                        fields=("client",),
                        name="uniq_open_renewal_request_per_client",
                    )
                ],
            },
        ),
    ]
