# Generated by Django 5.1.6 on 2026-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_clientrenewalrequest_processed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientportalaccess",
            name="last_selfservice_reissue_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
