# Generated by Django 5.1.6 on 2026-04-19 20:46

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_clientportalaccess_last_selfservice_reissue_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrenewalrequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.renewal_attachment_upload_to,
            ),
        ),
    ]
