# Generated by Django 5.1.6 on 2026-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_clientrenewalrequest_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrenewalrequest",
            name="attachment_original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
