# Generated by Django 5.1.6 on 2026-08-13 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключён'), ('deleted', 'Удалён')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт клиента',
                'verbose_name_plural': 'Аккаунты клиентов',
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('unknown', 'Не указано'), ('ios', 'iPhone / iPad'), ('android', 'Android'), ('macos', 'macOS'), ('windows', 'Windows'), ('linux', 'Linux'), ('other', 'Другое')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('disabled', 'Отключено'), ('deleted', 'Удалено')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customeraccount')),
            ],
            options={
                'verbose_name': 'Устройство клиента',
                'verbose_name_plural': 'Устройства клиентов',
                'ordering': ('account_id', 'name', 'id'),
            },
        ),
    ]
