# Generated by Django 5.1.6 on 2026-08-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_legacy_vpn_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='vpn_traffic_limit_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
