# Generated by Django 5.1.6 on 2026-09-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='expiration_reminder_days',
            field=models.CharField(default='7,3,1', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='expiration_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_new_renewal_requests',
            field=models.BooleanField(default=True),
        ),
    ]
